//Nextgen global lists
/datum/sanity/proc/pick_quote_40()
	var/static/list/sanity_quotes_40 = list(
		"Вы слышите, как в вентиляции что-то стучит когтями.",
		"Кто-то наблюдает за тобой.",
		"Вы чувствуете легкое покалывание.",
		"Вы слышите тяжелое дыхание за спиной.",
		"Вы утомлены.",
		"Вашу голову наполняет пульсируящая боль.",
		"Вам нужно закурить.",
		"Вы - самый великий человек на корабле.",
		"Все сошли с ума.",
		"Вы - единственный здравомыслящий на этом корабле!",
		"Вы слышите, как стучит ваше собственное сердце.",
		"Кто-то шепчется за вашей спиной.",
		"Все вас осуждают.",  // Twich streamer qoute
		"Паук пробегает между ваших ног и исчезает.",
		"Кто-то сказал ваше имя. Но когда вы обернулись, вы увидели лишь пыль.",
		"В воздухе чувствуется железный привкус. Это медь..?",
		"Ничего не изменилось. Но ты знаешь, что это не так.",
		"Они что-то подмешивают в воду. Что-то, что заставляет вас забывать.",
		"Вас тесно в вашей коже.",
		"Ваша одежда душит вас.",
		"Это всего лишь плохой день. Это всего лишь плохой день.",
		"Когда вам в последний раз снился хороший сон?",
		"Ваши зубы чешутся.",
		"Вы не можете перестать дергать ногой.",  // nadmozg
		"Это уже слишком.",
		"You need a fix. Just something to take away the edge.",  // IDK ANTON HELP PLS
		"Вы учуяли что-то, но не понимаете что.",
		"Звуки иллюзорны, они покидают ваше сознание.",
		"Прочистите горло, моргните, схватитесь за реальность и продолжайте.",
		"Вам кажется, что вы понимаете, почему этот корабль называют проклятым.",
		"Здесь что-то не так.",
		"Dark thoughts shimmer in your mind, drowned in an overwhelming sense of deja vu.", // ANTON HELP PLS
		"Посчитай до десяти. Сделай вдох. Ты сможешь.",
		"Вы устали, но сон не поможет вам отдохнуть.",
		"Так много людей погибло, исследуя Глубокий Космос, почему вас ждет иная судьба?",
		"Вы чувствуете что-то у себя в горле.",
		"Вам нужно побыть одному.",
		"Почему все механизмы на этом корабле выглядят по-разному?",
		"У тех бродяг действительно странные надписи на ID-картах. Сколько этому кораблю лет? Какова ВАША роль в его судьбе?",
		"В конце дня ты расслабишься и отдохнешь. Но сейчас есть работа, и ее надо выполнить.",
		"Тень дрожит.",
		"Что-то находится в вашей слепой зоне. Как долго оно там было?",
		"Однажды вы выйдете из всего этого дерьма с достаточной суммой, чтобы купить дом. Однажды.",
		"Ваши нервы шалят, но вы себя контролируете.",
		"Продолжай. Не смотри по сторонам. Продолжай. Не смотри по сторонам.",
		"Оно под поверхностью.",
		"Вы вспоминаете имя, но оно ничего для вас не значит.",
		"Страх захватывает ваше тело. Храбрость покидает вас.",
		"А что если они правы?",
		"Ваш рот открывается, и вы что-то говорите самому себе. В полной тишине.",
		"Сама реальность кажется вам такой старой.",
		"Вы не важны.",
		"Далекое тиканье, затем тишина. Что это было?",
		"Вспышка небытия, искра пустоты - это только что произошло, и это все, что ты можешь об этом сказать.",
		"Ваша плоть зудит, а ваши кости хрупки.",
		"Все складывается в единый ритм.",
		"Conceal your weakness, pretend that there is nothing going on. Good, yes, like this.",
		"Вы это игнорируете. Это не имеет смысла, так что вы это игнорируете.",
		"Ты знаешь, кто ты, ты знаешь почему ты здесь, так что ты не будешь заботиться о деталях.",
		"Вы обещали купить ему напиток, но как его зовут? Подождите, кто он?",
		"Не спрашивай, не рассказывай, ты в порядке, точно так же, как и все остальные.",
		"Где-то в этом мире умер паук. К чему все это?",
		"Космос - последний рубеж, а мы - первооткрыватели новой эры. И все же мы застряли в мусоре, тараканах и идиотах.",
		"Закрой глаза. Помни имя. Действуй.",
		"Почему это имеет смысл?",
		"Истина открывается, но закывается прежде, чем ты можешь понять ее. Если погрузишься глубже, то снова ее обнаржужишь, но стоит ли оно того?",
		"Кто был здесь перед тобой, в твоей обуви, на твоем месте? Что они делают и где они сейчас?",
		"Слишком много информации, вы перегружены.",
		"Что-то гибнет.",
		"Где ты?",
		"Тебе нужна вера, чтобы ходить по этим коридорам. В Бога, в себя, во что-нибудь.",
		"Сделай вдох и убей революцию внутри себя.",
		"Ты просишь о силе. Никто не отвечает.",
		"Порезы уходят глубоко в ваш разум. Ваше здравомыслие протекает через раны.",
		"Дрогни, сбеги и вернись за добавкой.",
		"Сколько лет тараканам? Много ли они видели?",
		"Ты задаешь слишком много вопросов. Ты чувствуешь себя виноватым.",
		"Но они знают, они всегда знают. Признай это.",
		"Что-то внутри твоего черепа хрустнуло, но ты не чувствуешь боли.",
		"Любопытство - твой величайший грех.",
		"Бургер бы не помешал. Как и что-либо съедобное, кстати."
	)
	return pick(sanity_quotes_40)

/datum/sanity/proc/pick_quote_20()
	var/static/list/sanity_quotes_20
	if(!sanity_quotes_20)
		sanity_quotes_20 = list(
			"Everything is beginning to freeze. Not even the comfort of warmth wants you.",
			"Every part of you is twitching. Remaining still is death.",
			"They want you dead.",
			"A wave of exhaustion overtakes you. Give up.",
			"You realize that the waking world was always a dream. You have to find a way to wake up. Wake up. Wake up.",
			"Sleep isn't real.",
			"The people on this ship are not real. They do not deserve your kindness.",
			"Your existence is not welcomed on this ship.",
			"Memories once fond begin to fade from your mind. You question whether they were real to begin with.",
			"End it all.",
			"You begin to realize that drugs are the only escape from the agony that is existence.",
			"The walls are wrong. The walls are wrong!",
			"You have a strange urge to go North.",
			"Your teeth feel out of place. They should be in your stomach. ",
			"Nothing shall be well. And nothing shall be well. And no manner of things shall be well.",
			"You'll feel better when you sink your teeth into their backs. You're sure.",
			"It feels like you're breathing inside your own lungs.",
			"You hunger for something rich and red rich and red rich and red rich and red rich and r-",
			"Escaping from your purpose is impossible...",
			"Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. Seven times seven. ",
			"And so they laughed. They laughed. You know they laughed. You heard them laugh. They laughed. They laughed.",
			"Whenever you see a mirror, you feel like you can just reach out� and step through it.",
			"THEY ARE COMING THEY ARE COMING THEY ARE COMING",
			"No. Parts of you are crumbling. No. No!",
			"What is this? No� No!",
			"Something is scratching from behind your eyes, aching to get out.",
			"SHE EMBRACES ALL CHILDREN SHE EMBRACES ALL CHILDREN SHE EMBRACES ALL CHILDREN",
			"Shadows lie still, here where there is no sun to move them. Sometimes they shiver in the fluorescent light.",
			"They watch you with narrow eyes. What do they see?",
			"It echoes loudly through your skin, the rhythm of the world.",
			"It occurred to you that bolts can scream as well. But there is more to it, they sing.",
			"A prayer is what moves some machines. Not by words, but by actions, a rituals that bind the reality. A mantra to their only God.",
			"See them live, die, rot, all in the passage of a single moment. A glimpse of the life cycle.",
			"Turn your mind inward, with the clear mirror of the world. See your pitiful and wretched soul.",
			"There was something between the gun and its target.",
			"Sell your dreams, crash your happiness. Enjoy the ticking sound of this worlds insides.",
			"Now you see it, a sharp pain that only your mind can feel resonates in a picture of the perfect machine. Then you see the rust and damage, a dead God.",
			"Move towards the light, even if your skin burns away.",
			"You radiate a hunger for knowledge, your mind is overheated and can melt the bounds of reality. Time to observe.",
			"Stay with them. Hear the music.",
			"The ceiling is covered in dark slime, how can anyone have not noticed this before?",
			"You are not mad. You see the reality as it really is.",
			"You are clearly insane now, you can't even trust your eyes.",
			"Converge with shadows to dance under the moonlight of a dead planet.",
			"TODAY IS A GOOD DAY",
			"You know who you are. But who am I?",
			"Bash your head until it's good. But it's never good.",
			"Humanity is doomed, and so are you.",
			"Crave for salvation under the dead suns. It's all that we have.",
			"At the verge of your sanity, gasping for sense, you are visited by an extreme thought - what if all of this could have been avoided if you were kinder to those around you?",
			"ALL IS FINE",
			"YOU ARE A HAPPY INDIVIDUAL",
			"YOUR LIFE HAVE A MEANING",
			"Destroy it by any means, with all your force.",
			"Impatience breeds strength, a crimson craving is unleashed in your mind.",
			"Open your mind to the wind of rotten flesh and crimson bones. Regret it afterwards.",
			"You collide with concepts so obscure that you lose yourself for a minute. But no time has passed for the others.",
			"Restrain your dancing mind and focus!",
			"A gunshot, a cloaked figure, a knife in the back. An overkill.",
			"SEE BEHIND THE START",
			"WEEP FOR WHAT WAS LOST BY THOSE WHO BELIEVE IN YOU",
			"It is possible to consume the fabric of reality itself. It tastes of oranges.",
			"Communism is a valid choice for large human populations, and should be enforced globally.",
			"A stench of a poisoned mind. Yours.",
			"Everyone can read your thoughts. They are written on your face.",
			"What will people think of you when they find out?",
			"Your bones hurt. A superstructure inside you demands to be set free.",
			"An idea reigns over your mind now. You can't tell what it is, because it refuses to speak with you.",
			"Silence! Drown in silence!",
			"Repurpose your mind as a bar of lost souls. Listen to their stories.",
			"Before the start, the beginning of everything, was the End, and you are so close to witnessing it!",
			"You have no words. You just ate them up.",
			"Conquer the fields of madness with your bare hands, to find out if you are worthy.",
			"The beat goes on. It goes, and goes, until your head pops from the sound.",
			"The corridor seemed endless at one point, like it was a different place, or even another world.",
			"You must maintain it. You must be a part of it.",
			"The forbidden animals roam the land.",
			"The rules are written in blood. The very old blood of generations of idiots.",
			"You are coming home.",
			"The writings are here, behind your skull.",
			"YOU HAVE NO CHOICE"
		)
		for(var/i in 0 to 9)
			sanity_quotes_20 += "[i] is the number."
	return pick(sanity_quotes_20)

/datum/sanity/proc/pick_emote_20()
	var/static/list/emotes = list(
		"grumbles.",
		"mutters.",
		"groans."
	)
	return pick(emotes)

/datum/sanity/proc/pick_emote_40()
	var/static/list/emotes = list(
		"stares.",
		"sighs.",
		"frowns.",
		"glares."
	)
	return pick(emotes)

datum/sanity/proc/pick_sound()
	var/static/list/sanity_sounds_without_text = list(
		'sound/sanity/waterdrop.ogg',
		'sound/sanity/piano.ogg',
		'sound/sanity/limb_tear_off.ogg',
		'sound/sanity/slice.ogg',
		'sound/sanity/circsaw.ogg',
		'sound/sanity/hydraulic.ogg',
		'sound/sanity/glass_step.ogg',
		'sound/sanity/supermatter.ogg',
		list('sound/hallucinations/i_see_you1.ogg', "You feel the hair on your neck stand on end. Is there someone behind you?"),
		list('sound/sanity/heavy_footsteps.ogg', "What was that?!"),
		list('sound/sanity/screech.ogg', "You feel a chill run up your spine!"),
		list('sound/sanity/very_evil_laugh.ogg', "Your skin breaks out into goosebumps.")
	)
	return pick(sanity_sounds_without_text)
